In [1]:
import tushare as ts
import pandas as pd
pro = ts.pro_api()
df=ts.get_stock_basics()

In [3]:
data = pro.query('stock_basic', exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')
df2 = pd.DataFrame()
for code in data['ts_code']:
    df = pro.daily(ts_code=code,start_date='20200915', end_date='20200929')
    df1 = pd.DataFrame(data = df, columns = ['ts_code','trade_date','change'])
    for change in df['change']:
        if change >= 10:
            df2 = df2.append(df1)
            print(df2)
   
print('end..............................')
df2.to_csv('222222.csv')

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
5   000661.SZ   20200922    3.17
6   000661.SZ   20200921    3.91
7   000661.SZ   20200918   -1.10
8   000661.SZ   20200917    1.55
9   000661.SZ   20200916  -21.91
10  000661.SZ   20200915   11.74
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
5   000661.SZ   20200922    3.17
6   000661.SZ   20200921    3.91
7   000661.SZ   20200918   -1.10
8   000661.SZ   20200917    1.55
9   000661.SZ   20200916  -21.91
10  000661.SZ   20200915   11.74
0   002594.SZ   20200929    1.49
1   002594.SZ   20200928    1.31
2   002594.SZ   20200925   -1.31
3   002594.SZ   20200924   -4.00
4   002594.SZ   20200923    3.63
5   002594.SZ   20200922    1.00
6   002594.SZ   20200921   -9.73
7   002594.SZ   20200918   -0.44
8   002594.SZ   20200917   10.54
9   002594.SZ   20200916    4.10
10  002594.SZ   20200915    8.80
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
5   000661.SZ   20200922    3.17
6   000661.SZ   20200921    3.91
7   000661.SZ   20200918   -1.10
8   000661.SZ   20200917    1.55
9   000661.SZ   20200916  -21.91
10  000661.SZ   20200915   11.74
0   002594.SZ   20200929    1.49
1   002594.SZ   20200928    1.31
2   002594.SZ   20200925   -1.31
3   002594.SZ   20200924   -4.00
4   002594.SZ   20200923    3.63
5   002594.SZ   20200922    1.00
6   002594.SZ   20200921   -9.73
7   002594.SZ   20200918   -0.44
8   002594.SZ   20200917   10.54
9   002594.SZ   20200916    4.10
10  002594.SZ   20200915    8.80
0   002821.SZ   20200929   -1.02
1   002821.SZ   20200928   -0.07
2   002821.SZ   20200925    9.72
3   002821.SZ   20200924   -3.82
4   002821.SZ   20200923   12.07
5   002821.SZ   20200922    2.42
6   002821.SZ   20200921    0.00
7   002821.SZ   20200918    5.48
8   002821.SZ   20200917   -2.91
9   002821.SZ   20200916   -5.39
10  002821.SZ   20200915   -2.63
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
5   000661.SZ   20200922    3.17
6   000661.SZ   20200921    3.91
7   000661.SZ   20200918   -1.10
8   000661.SZ   20200917    1.55
9   000661.SZ   20200916  -21.91
10  000661.SZ   20200915   11.74
0   002594.SZ   20200929    1.49
1   002594.SZ   20200928    1.31
2   002594.SZ   20200925   -1.31
3   002594.SZ   20200924   -4.00
4   002594.SZ   20200923    3.63
5   002594.SZ   20200922    1.00
6   002594.SZ   20200921   -9.73
7   002594.SZ   20200918   -0.44
8   002594.SZ   20200917   10.54
9   002594.SZ   20200916    4.10
10  002594.SZ   20200915    8.80
0   002821.SZ   20200929   -1.02
1   002821.SZ   20200928   -0.07
2   002821.SZ   20200925    9.72
3   002821.SZ   20200924   -3.82
4   002821.SZ   20200923   12.07
5   002821.SZ   20200922    2.42
6   002821.SZ   20200921    0.00
7   002821.SZ   20200918    5.48
8   002821.SZ   20200917   -2.91
9   002821.SZ   20200916   -5.39
10  002821.SZ   20200915   -2.63
0   002977.SZ   20200929    7.30
1   002977.SZ   20200928    1.42
2   002977.SZ   20200925    1.30
3   002977.SZ   20200924   -4.22
4   002977.SZ   20200923    1.60
5   002977.SZ   20200922   -4.81
6   002977.SZ   20200921   10.86
7   002977.SZ   20200918    0.97
8   002977.SZ   20200917   -0.07
9   002977.SZ   20200916   -2.93
10  002977.SZ   20200915   -1.20
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
5   000661.SZ   20200922    3.17
6   000661.SZ   20200921    3.91
7   000661.SZ   20200918   -1.10
8   000661.SZ   20200917    1.55
9   000661.SZ   20200916  -21.91
10  000661.SZ   20200915   11.74
0   002594.SZ   20200929    1.49
1   002594.SZ   20200928    1.31
2   002594.SZ   20200925   -1.31
3   002594.SZ   20200924   -4.00
4   002594.SZ   20200923    3.63
5   002594.SZ   20200922    1.00
6   002594.SZ   20200921   -9.73
7   002594.SZ   20200918   -0.44
8   002594.SZ   20200917   10.54
9   002594.SZ   20200916    4.10
10  002594.SZ   20200915    8.80
0   002821.SZ   20200929   -1.02
1   002821.SZ   20200928   -0.07
2   002821.SZ   20200925    9.72
3   002821.SZ   20200924   -3.82
4   002821.SZ   20200923   12.07
5   002821.SZ   20200922    2.42
6   002821.SZ   20200921    0.00
7   002821.SZ   20200918    5.48
8   002821.SZ   20200917   -2.91
9   002821.SZ   20200916   -5.39
10  002821.SZ   20200915   -2.63
0   002977.SZ   20200929    7.30
1   002977.SZ   20200928    1.42
2   002977.SZ   20200925    1.30
3   002977.SZ   20200924   -4.22
4   002977.SZ   20200923    1.60
5   002977.SZ   20200922   -4.81
6   002977.SZ   20200921   10.86
7   002977.SZ   20200918    0.97
8   002977.SZ   20200917   -0.07
9   002977.SZ   20200916   -2.93
10  002977.SZ   20200915   -1.20
0   002985.SZ   20200929    2.19
1   002985.SZ   20200928   -0.82
2   002985.SZ   20200925    0.03
3   002985.SZ   20200924   -8.42
4   002985.SZ   20200923    2.22
5   002985.SZ   20200922   -3.72
6   002985.SZ   20200921    1.05
7   002985.SZ   20200918    6.92
8   002985.SZ   20200917   10.03
9   002985.SZ   20200916   -5.70
10  002985.SZ   20200915    5.25
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
1   003005.SZ   20200928   -5.51
2   003005.SZ   20200925    5.55
3   003005.SZ   20200924    5.04
4   003005.SZ   20200923    4.58
5   003005.SZ   20200922   14.01

[61 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
0   003007.SZ   20200929   -3.17
1   003007.SZ   20200928   -4.08
2   003007.SZ   20200925    3.71
3   003007.SZ   20200924    3.37
4   003007.SZ   20200923   10.30

[66 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
0   003008.SZ   20200929   -3.88
1   003008.SZ   20200928   -4.62
2   003008.SZ   20200925   -2.02
3   003008.SZ   20200924    4.38
4   003008.SZ   20200923   13.38

[71 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300033.SZ   20200921   -5.40
7   300033.SZ   20200918   14.06
8   300033.SZ   20200917   -2.04
9   300033.SZ   20200916   -3.62
10  300033.SZ   20200915    3.52

[82 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300122.SZ   20200921    0.19
7   300122.SZ   20200918    1.04
8   300122.SZ   20200917   -1.92
9   300122.SZ   20200916   -2.85
10  300122.SZ   20200915    2.92

[93 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300454.SZ   20200921   -3.43
7   300454.SZ   20200918    4.57
8   300454.SZ   20200917   -1.46
9   300454.SZ   20200916   -0.98
10  300454.SZ   20200915   -2.80

[104 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300598.SZ   20200921   -1.10
7   300598.SZ   20200918   -3.69
8   300598.SZ   20200917   13.78
9   300598.SZ   20200916   -5.62
10  300598.SZ   20200915    0.81

[115 rows x 3 columns]

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300601.SZ   20200921   -2.50
7   300601.SZ   20200918    2.88
8   300601.SZ   20200917   -3.04
9   300601.SZ   20200916   -3.92
10  300601.SZ   20200915    7.38

[126 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300613.SZ   20200921   -1.26
7   300613.SZ   20200918    5.58
8   300613.SZ   20200917   12.14
9   300613.SZ   20200916   -2.57
10  300613.SZ   20200915   -2.20

[137 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300661.SZ   20200921  -10.01
7   300661.SZ   20200918    2.56
8   300661.SZ   20200917   12.00
9   300661.SZ   20200916   -1.74
10  300661.SZ   20200915    4.88

[148 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300677.SZ   20200921   -5.80
7   300677.SZ   20200918    5.90
8   300677.SZ   20200917   -0.28
9   300677.SZ   20200916   -1.00
10  300677.SZ   20200915    4.59

[159 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300750.SZ   20200921   -0.10
7   300750.SZ   20200918   -0.37
8   300750.SZ   20200917    6.14
9   300750.SZ   20200916   -2.44
10  300750.SZ   20200915    1.92

[170 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300760.SZ   20200921   -4.30
7   300760.SZ   20200918    6.30
8   300760.SZ   20200917  -10.56
9   300760.SZ   20200916  -10.00
10  300760.SZ   20200915    1.28

[181 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300782.SZ   20200921   -7.15
7   300782.SZ   20200918    3.54
8   300782.SZ   20200917   22.03
9   300782.SZ   20200916   -0.87
10  300782.SZ   20200915   17.45

[192 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300782.SZ   20200921   -7.15
7   300782.SZ   20200918    3.54
8   300782.SZ   20200917   22.03
9   300782.SZ   20200916   -0.87
10  300782.SZ   20200915   17.45

[203 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300841.SZ   20200921   -9.30
7   300841.SZ   20200918   59.50
8   300841.SZ   20200917    5.68
9   300841.SZ   20200916  -26.83
10  300841.SZ   20200915   52.75

[214 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300841.SZ   20200921   -9.30
7   300841.SZ   20200918   59.50
8   300841.SZ   20200917    5.68
9   300841.SZ   20200916  -26.83
10  300841.SZ   20200915   52.75

[225 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300841.SZ   20200921   -9.30
7   300841.SZ   20200918   59.50
8   300841.SZ   20200917    5.68
9   300841.SZ   20200916  -26.83
10  300841.SZ   20200915   52.75

[236 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300856.SZ   20200921    1.49
7   300856.SZ   20200918   -2.48
8   300856.SZ   20200917   -5.41
9   300856.SZ   20200916   11.70
10  300856.SZ   20200915   -2.42

[247 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300863.SZ   20200921   19.82
7   300863.SZ   20200918   -4.16
8   300863.SZ   20200917    6.16
9   300863.SZ   20200916   21.25
10  300863.SZ   20200915   17.71

[258 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300863.SZ   20200921   19.82
7   300863.SZ   20200918   -4.16
8   300863.SZ   20200917    6.16
9   300863.SZ   20200916   21.25
10  300863.SZ   20200915   17.71

[269 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300863.SZ   20200921   19.82
7   300863.SZ   20200918   -4.16
8   300863.SZ   20200917    6.16
9   300863.SZ   20200916   21.25
10  300863.SZ   20200915   17.71

[280 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300864.SZ   20200921   -0.60
7   300864.SZ   20200918   -1.50
8   300864.SZ   20200917   -2.30
9   300864.SZ   20200916    7.70
10  300864.SZ   20200915    1.50

[291 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300866.SZ   20200921    6.55
7   300866.SZ   20200918   -1.50
8   300866.SZ   20200917   10.30
9   300866.SZ   20200916    0.01
10  300866.SZ   20200915    2.99

[302 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300869.SZ   20200921   -1.42
7   300869.SZ   20200918    3.67
8   300869.SZ   20200917   -7.22
9   300869.SZ   20200916   -1.97
10  300869.SZ   20200915   13.01

[313 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300869.SZ   20200921   -1.42
7   300869.SZ   20200918    3.67
8   300869.SZ   20200917   -7.22
9   300869.SZ   20200916   -1.97
10  300869.SZ   20200915   13.01

[324 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300869.SZ   20200921   -1.42
7   300869.SZ   20200918    3.67
8   300869.SZ   20200917   -7.22
9   300869.SZ   20200916   -1.97
10  300869.SZ   20200915   13.01

[335 rows x 3 columns]

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300870.SZ   20200921   -0.50
7   300870.SZ   20200918   -3.66
8   300870.SZ   20200917   -3.69
9   300870.SZ   20200916   16.40
10  300870.SZ   20200915   -1.13

[346 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300875.SZ   20200921   14.77
7   300875.SZ   20200918   -2.79
8   300875.SZ   20200917   -4.24
9   300875.SZ   20200916    6.04
10  300875.SZ   20200915    1.00

[357 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300875.SZ   20200921   14.77
7   300875.SZ   20200918   -2.79
8   300875.SZ   20200917   -4.24
9   300875.SZ   20200916    6.04
10  300875.SZ   20200915    1.00

[368 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   300877.SZ   20200921    3.23
7   300877.SZ   20200918   -2.65
8   300877.SZ   20200917   -3.14
9   300877.SZ   20200916    4.93
10  300877.SZ   20200915    0.73

[379 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
5   300886.SZ   20200922   -4.20
6   300886.SZ   20200921    0.80
7   300886.SZ   20200918   -8.21
8   300886.SZ   20200917  -13.79
9   300886.SZ   20200916   73.21

[389 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
5   300887.SZ   20200922    1.00
6   300887.SZ   20200921   -4.89
7   300887.SZ   20200918   -0.71
8   300887.SZ   20200917    4.70
9   300887.SZ   20200916   66.43

[399 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
4   300888.SZ   20200923   -3.75
5   300888.SZ   20200922    7.68
6   300888.SZ   20200921    5.48
7   300888.SZ   20200918  -16.75
8   300888.SZ   20200917   51.95

[408 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
5   300889.SZ   20200922   -2.26
6   300889.SZ   20200921    0.33
7   300889.SZ   20200918   -6.71
8   300889.SZ   20200917   -9.24
9   300889.SZ   20200916   36.15

[418 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
4   300890.SZ   20200923   -2.27
5   300890.SZ   20200922   -2.57
6   300890.SZ   20200921    3.12
7   300890.SZ   20200918    0.00
8   300890.SZ   20200917   45.31

[427 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
4   300891.SZ   20200923    0.17
5   300891.SZ   20200922   -0.61
6   300891.SZ   20200921   -0.26
7   300891.SZ   20200918   -2.68
8   300891.SZ   20200917   19.20

[436 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
8   300891.SZ   20200917   19.20
0   300892.SZ   20200929   -1.07
1   300892.SZ   20200928   -6.91
2   300892.SZ   20200925  -12.45
3   300892.SZ   20200924   50.34

[440 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
3   300892.SZ   20200924   50.34
0   300893.SZ   20200929   -4.07
1   300893.SZ   20200928   -3.54
2   300893.SZ   20200925    1.24
3   300893.SZ   20200924   27.63

[444 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
3   300893.SZ   20200924   27.63
0   300895.SZ   20200929   -3.58
1   300895.SZ   20200928   -0.90
2   300895.SZ   20200925   -9.59
3   300895.SZ   20200924   56.44

[448 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
1   300895.SZ   20200928   -0.90
2   300895.SZ   20200925   -9.59
3   300895.SZ   20200924   56.44
0   300896.SZ   20200929    2.30
1   300896.SZ   20200928  221.83

[450 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
3   300895.SZ   20200924   56.44
0   300896.SZ   20200929    2.30
1   300896.SZ   20200928  221.83
0   300897.SZ   20200929   -8.36
1   300897.SZ   20200928   25.02

[452 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   600519.SH   20200921  -28.20
7   600519.SH   20200918   24.48
8   600519.SH   20200917  -54.58
9   600519.SH   20200916  -34.90
10  600519.SH   20200915   -6.00

[463 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   600519.SH   20200921  -28.20
7   600519.SH   20200918   24.48
8   600519.SH   20200917  -54.58
9   600519.SH   20200916  -34.90
10  600519.SH   20200915   -6.00

[474 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   600763.SH   20200921    5.03
7   600763.SH   20200918    0.00
8   600763.SH   20200917   -6.90
9   600763.SH   20200916   -8.70
10  600763.SH   20200915    4.62

[485 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   601888.SH   20200921   -6.99
7   601888.SH   20200918    3.87
8   601888.SH   20200917   -5.13
9   601888.SH   20200916   -5.32
10  601888.SH   20200915    8.28

[496 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   603290.SH   20200921   -5.72
7   603290.SH   20200918    9.42
8   603290.SH   20200917   17.36
9   603290.SH   20200916   -4.30
10  603290.SH   20200915    4.01

[507 rows x 3 columns]

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   603392.SH   20200921   -4.03
7   603392.SH   20200918    1.36
8   603392.SH   20200917    4.45
9   603392.SH   20200916   -4.65
10  603392.SH   20200915    2.88

[518 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   603444.SH   20200921  -13.26
7   603444.SH   20200918   27.87
8   603444.SH   20200917    3.70
9   603444.SH   20200916    8.52
10  603444.SH   20200915    5.88

[529 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   603444.SH   20200921  -13.26
7   603444.SH   20200918   27.87
8   603444.SH   20200917    3.70
9   603444.SH   20200916    8.52
10  603444.SH   20200915    5.88

[540 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[551 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[562 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[573 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[584 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[595 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[606 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605009.SH   20200921   14.44
7   605009.SH   20200918   13.13
8   605009.SH   20200917   11.93
9   605009.SH   20200916   10.85
10  605009.SH   20200915    9.86

[617 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605128.SH   20200921    0.00
7   605128.SH   20200918   -3.10
8   605128.SH   20200917   -2.77
9   605128.SH   20200916    3.36
10  605128.SH   20200915   10.26

[628 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605168.SH   20200921   -0.20
7   605168.SH   20200918   19.96
8   605168.SH   20200917   16.12
9   605168.SH   20200916    3.10
10  605168.SH   20200915    0.04

[639 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   605168.SH   20200921   -0.20
7   605168.SH   20200918   19.96
8   605168.SH   20200917   16.12
9   605168.SH   20200916    3.10
10  605168.SH   20200915    0.04

[650 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
5   605369.SH   20200922    6.07
6   605369.SH   20200921    5.52
7   605369.SH   20200918    5.01
8   605369.SH   20200917    4.56
9   605369.SH   20200916   13.93

[660 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688012.SH   20200921    0.25
7   688012.SH   20200918    3.13
8   688012.SH   20200917    5.69
9   688012.SH   20200916   -3.35
10  688012.SH   20200915   11.36

[671 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
8   688012.SH   20200917    5.69
9   688012.SH   20200916   -3.35
10  688012.SH   20200915   11.36
0   688013.SH   20200929   -4.46
1   688013.SH   20200928   22.09

[673 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688017.SH   20200921    0.89
7   688017.SH   20200918    0.04
8   688017.SH   20200917   -2.75
9   688017.SH   20200916   -5.00
10  688017.SH   20200915   11.38

[684 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688018.SH   20200921    0.69
7   688018.SH   20200918    4.38
8   688018.SH   20200917    9.97
9   688018.SH   20200916   -0.19
10  688018.SH   20200915    2.19

[695 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688019.SH   20200921   -2.74
7   688019.SH   20200918    7.00
8   688019.SH   20200917    5.00
9   688019.SH   20200916    1.50
10  688019.SH   20200915   20.53

[706 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688019.SH   20200921   -2.74
7   688019.SH   20200918    7.00
8   688019.SH   20200917    5.00
9   688019.SH   20200916    1.50
10  688019.SH   20200915   20.53

[717 rows x 3 columns]

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688023.SH   20200921   -6.82
7   688023.SH   20200918    5.92
8   688023.SH   20200917   10.81
9   688023.SH   20200916  -11.46
10  688023.SH   20200915  -11.08

[728 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688023.SH   20200921   -6.82
7   688023.SH   20200918    5.92
8   688023.SH   20200917   10.81
9   688023.SH   20200916  -11.46
10  688023.SH   20200915  -11.08

[739 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688023.SH   20200921   -6.82
7   688023.SH   20200918    5.92
8   688023.SH   20200917   10.81
9   688023.SH   20200916  -11.46
10  688023.SH   20200915  -11.08

[750 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688027.SH   20200921   -5.00
7   688027.SH   20200918   12.44
8   688027.SH   20200917    7.86
9   688027.SH   20200916   -3.30
10  688027.SH   20200915    4.90

[761 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688027.SH   20200921   -5.00
7   688027.SH   20200918   12.44
8   688027.SH   20200917    7.86
9   688027.SH   20200916   -3.30
10  688027.SH   20200915    4.90

[772 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688050.SH   20200921   -4.75
7   688050.SH   20200918   10.01
8   688050.SH   20200917   -3.51
9   688050.SH   20200916   -4.50
10  688050.SH   20200915   -2.49

[783 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688050.SH   20200921   -4.75
7   688050.SH   20200918   10.01
8   688050.SH   20200917   -3.51
9   688050.SH   20200916   -4.50
10  688050.SH   20200915   -2.49

[794 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688060.SH   20200921   -0.77
7   688060.SH   20200918   -9.96
8   688060.SH   20200917   23.63
9   688060.SH   20200916   -1.88
10  688060.SH   20200915    1.11

[805 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688095.SH   20200921  -16.95
7   688095.SH   20200918   33.50
8   688095.SH   20200917  -10.97
9   688095.SH   20200916    2.76
10  688095.SH   20200915    3.31

[816 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688095.SH   20200921  -16.95
7   688095.SH   20200918   33.50
8   688095.SH   20200917  -10.97
9   688095.SH   20200916    2.76
10  688095.SH   20200915    3.31

[827 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688111.SH   20200921   -5.25
7   688111.SH   20200918    2.89
8   688111.SH   20200917    7.10
9   688111.SH   20200916   -6.18
10  688111.SH   20200915    5.28

[838 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
2   688127.SH   20200925   -4.60
3   688127.SH   20200924   -1.38
4   688127.SH   20200923    1.40
5   688127.SH   20200922   -2.35
6   688127.SH   20200921   19.42

[845 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688155.SH   20200921   -0.79
7   688155.SH   20200918   -4.06
8   688155.SH   20200917   10.94
9   688155.SH   20200916    0.05
10  688155.SH   20200915    0.77

[856 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
1   688156.SH   20200928   -0.82
2   688156.SH   20200925   -0.98
3   688156.SH   20200924   -0.62
4   688156.SH   20200923   -1.85
5   688156.SH   20200922   13.39

[862 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688169.SH   20200921    3.01
7   688169.SH   20200918   42.00
8   688169.SH   20200917    4.01
9   688169.SH   20200916   35.98
10  688169.SH   20200915  -19.22

[873 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688169.SH   20200921    3.01
7   688169.SH   20200918   42.00
8   688169.SH   20200917    4.01
9   688169.SH   20200916   35.98
10  688169.SH   20200915  -19.22

[884 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688169.SH   20200921    3.01
7   688169.SH   20200918   42.00
8   688169.SH   20200917    4.01
9   688169.SH   20200916   35.98
10  688169.SH   20200915  -19.22

[895 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688169.SH   20200921    3.01
7   688169.SH   20200918   42.00
8   688169.SH   20200917    4.01
9   688169.SH   20200916   35.98
10  688169.SH   20200915  -19.22

[906 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688185.SH   20200921    0.50
7   688185.SH   20200918    6.86
8   688185.SH   20200917  -18.50
9   688185.SH   20200916   -3.46
10  688185.SH   20200915  -10.80

[917 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688185.SH   20200921    0.50
7   688185.SH   20200918    6.86
8   688185.SH   20200917  -18.50
9   688185.SH   20200916   -3.46
10  688185.SH   20200915  -10.80

[928 rows x 3 columns]

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688188.SH   20200921    4.02
7   688188.SH   20200918    5.48
8   688188.SH   20200917   -2.57
9   688188.SH   20200916    2.47
10  688188.SH   20200915    1.19

[939 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688188.SH   20200921    4.02
7   688188.SH   20200918    5.48
8   688188.SH   20200917   -2.57
9   688188.SH   20200916    2.47
10  688188.SH   20200915    1.19

[950 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688298.SH   20200921    3.48
7   688298.SH   20200918   13.09
8   688298.SH   20200917    6.11
9   688298.SH   20200916   -1.49
10  688298.SH   20200915    4.65

[961 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688298.SH   20200921    3.48
7   688298.SH   20200918   13.09
8   688298.SH   20200917    6.11
9   688298.SH   20200916   -1.49
10  688298.SH   20200915    4.65

[972 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
3   688301.SH   20200924  -10.88
4   688301.SH   20200923    2.58
5   688301.SH   20200922   -1.20
6   688301.SH   20200921    9.40
7   688301.SH   20200918   40.50

[980 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688318.SH   20200921   -7.00
7   688318.SH   20200918   14.21
8   688318.SH   20200917    5.61
9   688318.SH   20200916   -5.87
10  688318.SH   20200915    0.72

[991 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688366.SH   20200921   -4.15
7   688366.SH   20200918    0.22
8   688366.SH   20200917    5.85
9   688366.SH   20200916   -2.02
10  688366.SH   20200915    2.07

[1002 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688390.SH   20200921    0.99
7   688390.SH   20200918   -6.86
8   688390.SH   20200917    2.50
9   688390.SH   20200916   14.20
10  688390.SH   20200915   -0.38

[1013 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688390.SH   20200921    0.99
7   688390.SH   20200918   -6.86
8   688390.SH   20200917    2.50
9   688390.SH   20200916   14.20
10  688390.SH   20200915   -0.38

[1024 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688399.SH   20200921    4.38
7   688399.SH   20200918   27.18
8   688399.SH   20200917    5.01
9   688399.SH   20200916   -2.66
10  688399.SH   20200915    7.45

[1035 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688399.SH   20200921    4.38
7   688399.SH   20200918   27.18
8   688399.SH   20200917    5.01
9   688399.SH   20200916   -2.66
10  688399.SH   20200915    7.45

[1046 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688500.SH   20200921   -0.98
7   688500.SH   20200918   -2.97
8   688500.SH   20200917   10.22
9   688500.SH   20200916   -1.19
10  688500.SH   20200915    0.80

[1057 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688520.SH   20200921    0.13
7   688520.SH   20200918   -2.22
8   688520.SH   20200917   10.13
9   688520.SH   20200916   -1.16
10  688520.SH   20200915    0.82

[1068 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
1   688526.SH   20200928   -1.69
2   688526.SH   20200925   -1.95
3   688526.SH   20200924   -1.23
4   688526.SH   20200923    4.00
5   688526.SH   20200922   19.89

[1074 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
2   688536.SH   20200925    0.45
3   688536.SH   20200924    2.36
4   688536.SH   20200923   28.63
5   688536.SH   20200922   28.01
6   688536.SH   20200921   89.29

[1081 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
2   688536.SH   20200925    0.45
3   688536.SH   20200924    2.36
4   688536.SH   20200923   28.63
5   688536.SH   20200922   28.01
6   688536.SH   20200921   89.29

[1088 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
2   688536.SH   20200925    0.45
3   688536.SH   20200924    2.36
4   688536.SH   20200923   28.63
5   688536.SH   20200922   28.01
6   688536.SH   20200921   89.29

[1095 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
5   688577.SH   20200922   -3.26
6   688577.SH   20200921   -1.02
7   688577.SH   20200918   -7.67
8   688577.SH   20200917    5.16
9   688577.SH   20200916   28.21

[1105 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
6   688580.SH   20200921   -0.14
7   688580.SH   20200918   -1.06
8   688580.SH   20200917    0.21
9   688580.SH   20200916   -1.83
10  688580.SH   20200915    0.43

[1116 rows x 3 columns]
      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
8   688580.SH   20200917    0.21
9   688580.SH   20200916   -1.83
10  688580.SH   20200915    0.43
0   688585.SH   20200929   -1.76
1   688585.SH   20200928   13.86

[1118 rows x 3 columns]

      ts_code trade_date  change
0   000661.SZ   20200929    4.99
1   000661.SZ   20200928    0.50
2   000661.SZ   20200925   -3.80
3   000661.SZ   20200924   -9.20
4   000661.SZ   20200923    9.72
..        ...        ...     ...
10  688580.SH   20200915    0.43
0   688585.SH   20200929   -1.76
1   688585.SH   20200928   13.86
0   688595.SH   20200929    6.99
1   688595.SH   20200928   39.99

[1120 rows x 3 columns]
end..............................